### ISSUE TITLE
→_→

### ISSUE THREAD

**Issue by wdssmq** [arronf2e/Z-blog#1]
Z-Blog

Z-Blog和Z-BlogPHP是由RainbowSoft Studio团队开发的博客程序。

    Fuzhou, Fujian, China https://www.zblogcn.com/ 
https://github.com/zblogcn

**Comment by arronf2e** [comment]
@wdssmq pu....只是以自己姓首字母命名了，没注意哈哈，而且这个名字的项目很多呢=，=
